import { notFound, redirect } from 'next/navigation'
import Link from 'next/link'
import { desc } from 'drizzle-orm'
import { db } from '@/db/client'
import { profiles, webhookEvents } from '@/db/schema'
import { callbackUrl, config, configIssues } from '@/lib/config'
import { getSandboxScenarios } from '@/lib/jobo/client'
import type { SandboxScenario } from '@/lib/jobo/sandbox'
import { readSnippet } from '@/lib/snippets'
import {
  getTutorialState,
  latestWatchTarget,
  stepIndex,
  tutorialRecap,
  TUTORIAL_STEPS,
  type TutorialSlug,
  type TutorialState
} from '@/lib/tutorial'
import { SetupShell, StepColumns } from '@/components/SetupShell'
import { Stepper } from '@/components/Stepper'
import { TeachPanel } from '@/components/TeachPanel'
import { CodeBlock } from '@/components/CodeBlock'
import { ChecklistCard, type ChecklistItem } from '@/components/ChecklistCard'
import { SuccessPanel } from '@/components/SuccessPanel'
import { PreflightRunner } from '@/components/PreflightRunner'
import { ResumeUpload } from '@/components/ResumeUpload'
import { ApplyForm } from '@/components/ApplyForm'
import { StatusTimeline } from '@/components/StatusTimeline'
import { ApplicationInspector, loadApplicationView } from '@/components/ApplicationInspector'
import { PollingRefresher } from '@/components/PollingRefresher'
import { ButtonLink, Panel, relativeTime } from '@/components/ui'
import { isTerminal } from '@/lib/status'

export const dynamic = 'force-dynamic'

/**
 * The tutorial. One dynamic route, five steps, and no stored progress —
 * every gate is derived from the same state the integration produces.
 */
export default async function LearnStepPage({
  params,
  searchParams
}: {
  params: Promise<{ step: string }>
  searchParams: Promise<{ app?: string }>
}) {
  const { step } = await params
  const slug = step as TutorialSlug
  const meta = TUTORIAL_STEPS.find((entry) => entry.slug === slug)
  if (!meta) notFound()

  const state = getTutorialState()
  const position = stepIndex(slug)

  // Locked steps redirect to wherever the developer actually is.
  if (position > state.highestAvailableStep) {
    redirect(`/learn/${TUTORIAL_STEPS[state.currentStep - 1].slug}`)
  }

  const shell = {
    eyebrow: `Step ${position} of 5`,
    title: meta.label,
    stepper: <Stepper state={state} />
  }

  switch (slug) {
    case 'connect':
      return <ConnectStep shell={shell} state={state} />
    case 'profile':
      return <ProfileStep shell={shell} state={state} />
    case 'create':
      return <CreateStep shell={shell} />
    case 'watch':
      return <WatchStep shell={shell} state={state} appId={(await searchParams).app} />
    case 'done':
      return <DoneStep shell={shell} />
    default:
      notFound()
  }
}

interface ShellProps {
  eyebrow: string
  title: string
  stepper: React.ReactNode
}

function ContinueRow({
  done,
  href,
  label,
  waiting
}: {
  done: boolean
  href: string
  label: string
  waiting: string
}) {
  return (
    <div className="flex items-center gap-4 border-t hairline pt-6">
      {done ? (
        <ButtonLink href={href}>{label}</ButtonLink>
      ) : (
        <p className="text-sm text-ink-500">{waiting}</p>
      )}
    </div>
  )
}

// ─── Step 1 · Verify your setup ──────────────────────────────────────────────

const ENV_CHECKS: { key: string; title: string; description: string }[] = [
  {
    key: 'JOBO_API_KEY',
    title: 'Jobo API key',
    description: 'A jbe_test_ or jbe_live_ key. Master keys are rejected on Auto Apply routes.'
  },
  {
    key: 'JOBO_WEBHOOK_SECRET',
    title: 'Webhook signing secret',
    description:
      'The whsec_ account secret, generated by PUT /api/auto-apply/settings on the portal API and revealed exactly once.'
  },
  {
    key: 'PUBLIC_BASE_URL',
    title: 'Public callback origin',
    description:
      'The https origin Jobo calls back on — your tunnel in development. Restart the dev server after changing it.'
  },
  {
    key: 'RESUME_URL_SIGNING_SECRET',
    title: 'Resume URL signing secret',
    description: 'Signs the short-lived resume download links. Generate with openssl rand -base64 32.'
  },
  {
    key: 'OPENROUTER_API_KEY',
    title: 'OpenRouter key',
    description: 'Answers the open-ended questions your deterministic rules cannot.'
  }
]

function ConnectStep({ shell, state }: { shell: ShellProps; state: TutorialState }) {
  const issues = new Map(configIssues().map((issue) => [issue.key, issue.message]))

  const items: ChecklistItem[] = ENV_CHECKS.map((check) => ({
    key: check.key,
    title: check.title,
    state: issues.has(check.key) ? 'error' : 'done',
    description: (
      <>
        <code className="code-chip text-xs">{check.key}</code>
        <span className="ml-2">{issues.get(check.key) ?? check.description}</span>
      </>
    )
  }))

  const recentEvents = db
    .select({
      id: webhookEvents.id,
      type: webhookEvents.type,
      receivedAt: webhookEvents.receivedAt
    })
    .from(webhookEvents)
    .orderBy(desc(webhookEvents.receivedAt))
    .limit(5)
    .all()

  return (
    <SetupShell
      {...shell}
      description="Auto Apply needs four credentials and one thing money cannot buy: a public HTTPS origin on port 443 that Jobo's callbacks can actually reach."
    >
      <StepColumns
        main={
          <>
            <ChecklistCard
              title="Environment"
              description="Copy .env.example to .env.local and fill it in. The dev server reads it at boot."
              items={items}
            />
            <Panel title="Network preflight">
              <PreflightRunner />
            </Panel>
            <Panel
              title="Received callbacks"
              actions={
                <span className="text-xs text-ink-500">newest first</span>
              }
            >
              {recentEvents.length === 0 ? (
                <p className="text-sm text-ink-600">
                  Callbacks not received yet. Send a verification ping from the portal
                  (POST /api/auto-apply/settings/verify) to test the whole pipe — signature and all
                  — before spending a create quota.
                </p>
              ) : (
                <ul className="divide-y hairline text-sm">
                  {recentEvents.map((event) => (
                    <li key={event.id} className="flex items-center justify-between gap-3 py-2">
                      <code className="font-mono text-[13px] text-ink-800">
                        {event.type.replace('application.', '')}
                      </code>
                      <span className="text-xs text-ink-500">
                        <code className="font-mono">{event.id.slice(0, 16)}…</code> ·{' '}
                        {relativeTime(event.receivedAt)}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </Panel>
            <ContinueRow
              done={state.steps[0].done}
              href="/learn/profile"
              label="Continue to profiles"
              waiting="Environment values are missing or invalid — fix them above, restart the dev server, and refresh."
            />
          </>
        }
        rail={
          <>
            <TeachPanel eyebrow="The architecture" title="Auto Apply is profileless">
              <p>
                Jobo stores no candidate profile, uploads no resume, and generates no answers. The
                public API is four endpoints: create, list, get, cancel.
              </p>
              <p>
                Everything else happens in reverse: when Jobo&apos;s browser agent finds a form, it
                POSTs the fields to <em>your</em> callback and reads the answers out of your HTTP
                response — synchronously, inside a 120-second window. This app is that callback.
              </p>
            </TeachPanel>
            <TeachPanel eyebrow="Why https on 443" title="The SSRF guard is strict">
              <p>
                Jobo only calls a public HTTPS URL on port 443 whose DNS resolves to a public
                address, and follows no redirects. localhost can never work; neither can a tunnel
                on a custom port. This app validates the same rules at boot:
              </p>
            </TeachPanel>
            <CodeBlock
              label="lib/config.ts"
              language="ts"
              code={readSnippet(
                'lib/config.ts',
                "if (url.port && url.port !== '443')",
                'must be publicly resolvable',
                2
              )}
            />
          </>
        }
      />
    </SetupShell>
  )
}

// ─── Step 2 · Own the profile ────────────────────────────────────────────────

function ProfileStep({ shell, state }: { shell: ShellProps; state: TutorialState }) {
  const rows = db.select().from(profiles).orderBy(desc(profiles.createdAt)).all()
  const first = rows[0]

  return (
    <SetupShell
      {...shell}
      description="A profile is a parsed resume plus the freeform context open-ended questions are answered from. It lives in this app's database — Jobo never sees it, only the individual answers."
    >
      <StepColumns
        main={
          <>
            {first ? (
              <Panel title={first.name} eyebrow="Profile">
                <dl className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm sm:grid-cols-4">
                  {[
                    ['Email', first.data.personal.email || '—'],
                    ['Roles', String(first.data.work_experience.length)],
                    ['Education', String(first.data.education.length)],
                    ['Skills', String(first.data.skills.length)]
                  ].map(([label, value]) => (
                    <div key={label}>
                      <dt className="font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
                        {label}
                      </dt>
                      <dd className="mt-0.5 truncate text-ink-800">{value}</dd>
                    </div>
                  ))}
                </dl>
                <div className="mt-4 border-t hairline pt-4">
                  <p className="text-sm text-ink-600">
                    Open-ended questions (&ldquo;why do you want to work here?&rdquo;) are answered
                    from the freeform context — a resume does not contain that. Add a few lines
                    before applying.
                  </p>
                  <div className="mt-3">
                    <ButtonLink href={`/profiles/${first.id}`} variant="secondary" size="sm">
                      Edit profile and add context
                    </ButtonLink>
                  </div>
                </div>
              </Panel>
            ) : (
              <Panel title="Import a resume">
                <ResumeUpload redirectTo="/learn/profile" />
              </Panel>
            )}
            {first && (
              <Panel title="Add another resume" padding="md">
                <ResumeUpload redirectTo="/learn/profile" />
              </Panel>
            )}
            <ContinueRow
              done={state.steps[1].done}
              href="/learn/create"
              label="Continue to create"
              waiting="Import a resume to continue — a PDF with real text, not a scan."
            />
          </>
        }
        rail={
          <>
            <TeachPanel eyebrow="No Jobo request on this step" title="That absence is the lesson">
              <p>
                There is no profile endpoint to call — the contract deliberately leaves candidate
                data on your side. Jobo receives individual answer values during the callback and
                nothing else.
              </p>
            </TeachPanel>
            <TeachPanel eyebrow="Sensitive fields" title="Self-identification is never inferred">
              <p>
                Fields marked <code className="code-chip text-xs">sensitive: true</code> (EEO,
                veteran status, disability) are answered only from values a human typed into the
                profile editor. They are never sent to the model; absent a stored answer the app
                selects the form&apos;s own &ldquo;prefer not to say&rdquo; option or leaves the
                field blank.
              </p>
            </TeachPanel>
            <CodeBlock
              label="db/schema.ts"
              language="ts"
              code={readSnippet('db/schema.ts', 'Voluntary self-identification answers.', '$type<EeoAnswers>()')}
            />
          </>
        }
      />
    </SetupShell>
  )
}

// ─── Step 3 · Create an application ──────────────────────────────────────────

const CREATE_WIRE_SAMPLE = `POST /api/auto-apply/applications HTTP/1.1
Host: connect.jobo.world
X-Api-Key: jbe_test_...
Idempotency-Key: 3f6d1c2a-9d0e-4b7a-8f21-5a4c9e8b7d10
Content-Type: application/json

{
  "apply_url": "https://sandbox.jobo.world/ats/apply/...",
  "callback_url": "https://your-tunnel/api/jobo/webhook",
  "sandbox": true
}

HTTP/1.1 202 Accepted
Location: /api/auto-apply/applications/{id}

{ "id": "...", "status": "queued", "provider_name": "..." }`

async function CreateStep({ shell }: { shell: ShellProps }) {
  const available = db.select().from(profiles).orderBy(desc(profiles.createdAt)).all()

  let scenarios: SandboxScenario[] = []
  let sandboxAvailable = false
  let sandboxNote: string | null = null
  try {
    const response = await getSandboxScenarios()
    sandboxAvailable = response.available
    scenarios = response.scenarios.filter((scenario) => scenario.apply_url)
    if (!response.available) sandboxNote = 'the sandbox is not enabled on this deployment yet'
    else if (scenarios.length === 0) sandboxNote = 'no scenarios are published right now'
  } catch (error) {
    sandboxNote = `could not load scenarios (${error instanceof Error ? error.message : String(error)})`
  }

  return (
    <SetupShell
      {...shell}
      description="One POST with an Idempotency-Key. Jobo matches the ATS, opens the form in a real browser, and everything after this arrives at your callback."
    >
      <StepColumns
        main={
          <>
            <Panel title="Apply to a job">
              <ApplyForm
                profiles={available.map((p) => ({ id: p.id, name: p.name, isDefault: p.isDefault }))}
                scenarios={scenarios}
                sandboxAvailable={sandboxAvailable && scenarios.length > 0}
                sandboxNote={sandboxNote}
                defaultSandbox={config().DEFAULT_SANDBOX}
                callbackUrl={callbackUrl()}
                redirectPrefix="/learn/watch?app="
              />
            </Panel>
            <TeachPanel eyebrow="When create fails" title="The error taxonomy is part of the API">
              <ul className="list-disc space-y-1 pl-4">
                <li>
                  <code className="code-chip text-xs">auto_apply_coming_soon</code> — creation is
                  deployment-gated (503). The verification ping from step 1 still works.
                </li>
                <li>
                  <code className="code-chip text-xs">unsupported_ats</code> — no provider matched
                  the URL.
                </li>
                <li>
                  <code className="code-chip text-xs">unsafe_url</code> — the callback failed the
                  https/443/public-DNS rules.
                </li>
                <li>
                  <code className="code-chip text-xs">idempotency_key_reuse</code> — same key,
                  different body. Keys bind to the exact body for 24 hours.
                </li>
                <li>
                  <code className="code-chip text-xs">application_quota_exceeded</code> — 5 live
                  per 24h, 20 sandbox per hour, 5 in flight.
                </li>
              </ul>
            </TeachPanel>
          </>
        }
        rail={
          <>
            <TeachPanel eyebrow="The only request you make" title="Write the key before the call">
              <p>
                If the create times out you cannot know whether Jobo accepted it. The only safe
                retry reuses the exact same Idempotency-Key — which can only exist beforehand if
                you persisted it beforehand. This app inserts the local row first, always:
              </p>
            </TeachPanel>
            <CodeBlock
              label="app/actions/applications.ts"
              language="ts"
              code={readSnippet('app/actions/applications.ts', 'The ordering here is the point', '.run()')}
            />
            <CodeBlock label="The wire" language="http" code={CREATE_WIRE_SAMPLE} />
          </>
        }
      />
    </SetupShell>
  )
}

// ─── Step 4 · Answer the callback ────────────────────────────────────────────

async function WatchStep({
  shell,
  state,
  appId
}: {
  shell: ShellProps
  state: TutorialState
  appId?: string
}) {
  const targetId = appId ?? latestWatchTarget()?.id
  const view = targetId ? await loadApplicationView(targetId) : null

  const hasCorrection = view?.events.some((event) => (event.correctionRound ?? 0) > 0) ?? false

  return (
    <SetupShell
      {...shell}
      description="Your webhook is doing the work right now: verify the signature, dedupe by event id, generate answers inside the budget, and never — ever — return a non-2xx."
    >
      {view ? (
        <div className="space-y-6">
          <PollingRefresher
            active={!isTerminal(view.application.status) && view.application.status !== 'create_failed'}
          />
          <StatusTimeline application={view.application} events={view.events} />
          <StepColumns
            main={<ApplicationInspector view={view} />}
            rail={
              <>
                <TeachPanel eyebrow="The one fatal rule" title="Never return a non-2xx" tone="warn">
                  <p>
                    Unlike most webhooks, a non-2xx response is not retried — it fails the
                    application instantly with{' '}
                    <code className="font-mono text-xs">callback_rejected</code>. The 0s/5s/20s
                    retries fire for transport errors only. If your handler breaks, return{' '}
                    <code className="font-mono text-xs">200 {'{"action":"cancel"}'}</code>: a clean
                    cancel instead of a dead application.
                  </p>
                </TeachPanel>
                <CodeBlock
                  label="app/api/jobo/webhook/route.ts"
                  language="ts"
                  code={readSnippet(
                    'app/api/jobo/webhook/route.ts',
                    '*  1. NEVER RETURN A NON-2xx',
                    'is not.'
                  )}
                />
                <TeachPanel eyebrow="Replay protection" title="Dedupe is a UNIQUE constraint">
                  <p>
                    <code className="font-mono text-xs">X-Jobo-Webhook-Id</code> is stable across
                    retries, so this app uses the <code className="font-mono text-xs">evt_</code>{' '}
                    value as the primary key of its events table. Claiming an event is one{' '}
                    <code className="font-mono text-xs">INSERT … ON CONFLICT DO NOTHING</code> —
                    no check-then-act race.
                  </p>
                </TeachPanel>
                <TeachPanel eyebrow="Signature" title="You do not write the crypto">
                  <p>
                    HMAC-SHA256 over{' '}
                    <code className="font-mono text-xs">
                      utf8(eventId + &quot;.&quot; + timestamp + &quot;.&quot;) &#8214; rawBody
                    </code>
                    , constant-time compared against every{' '}
                    <code className="font-mono text-xs">v1=</code> entry, inside a 300s window —
                    all of it lives in{' '}
                    <code className="font-mono text-xs">@jobo-ai/autoapply</code>. Your side is the
                    two lines below: name the secret, and the handler hands you a verified event
                    plus the exact bytes that were signed.
                  </p>
                </TeachPanel>
                <CodeBlock
                  label="app/api/jobo/webhook/route.ts"
                  language="ts"
                  code={readSnippet(
                    'app/api/jobo/webhook/route.ts',
                    'let handler: ((request: Request)',
                    'secret: config().JOBO_WEBHOOK_SECRET,'
                  )}
                />
                <TeachPanel
                  eyebrow="Correction rounds"
                  title={hasCorrection ? 'One happened on this application' : 'When answers are rejected'}
                >
                  <p>
                    Invalid answers come back as a new callback with{' '}
                    <code className="font-mono text-xs">command_errors</code> and the FULL field
                    list — your reply must be a complete snapshot, not a delta. After three rounds
                    the application fails with{' '}
                    <code className="font-mono text-xs">correction_limit_exceeded</code>, which is
                    why this app validates locally with a port of Jobo&apos;s own validator before
                    responding.
                  </p>
                </TeachPanel>
              </>
            }
          />
          <ContinueRow
            done={state.steps[3].done}
            href="/learn/done"
            label="Continue to wrap up"
            waiting="Waiting for the terminal event — the page refreshes itself while the application is open."
          />
        </div>
      ) : (
        <Panel title="No application to watch">
          <p className="text-sm text-ink-600">
            Application not found or not created yet.{' '}
            <Link href="/learn/create" className="font-medium text-brand hover:text-brand-deep hover:underline">
              Create one
            </Link>{' '}
            and come back — this page follows it live.
          </p>
        </Panel>
      )}
    </SetupShell>
  )
}

// ─── Step 5 · Go live ────────────────────────────────────────────────────────

function DoneStep({ shell }: { shell: ShellProps }) {
  const recap = tutorialRecap()

  const nextSteps: ChecklistItem[] = [
    {
      key: 'live',
      title: 'Rotate to live mode',
      description:
        'Swap jbe_test_ for jbe_live_ in .env.local and apply to a real job URL. Live quota is 5 creates per 24 hours.',
      action: undefined
    },
    {
      key: 'correction',
      title: 'Trigger a correction round',
      description:
        'Edit your profile so an option cannot match (an unusual country spelling works), apply again, and watch the retry prompt carry you_sent and allowed_values.',
      action: (
        <ButtonLink href="/learn/create" variant="secondary" size="sm">
          Apply again
        </ButtonLink>
      )
    },
    {
      key: 'harden',
      title: 'Harden for production',
      description:
        'A stable HTTPS origin instead of a quick tunnel, alerting on the delivery-attempts view, and a queue if your answer path outgrows one process.'
    },
    {
      key: 'files',
      title: 'Read the four ★ files',
      description:
        'app/api/jobo/webhook/route.ts · lib/answers/validate.ts · lib/answers/index.ts — the whole integration is those three, because @jobo-ai/autoapply is the rest.'
    }
  ]

  return (
    <SetupShell
      {...shell}
      description="You have watched the whole contract execute. Everything from here is scale and polish."
    >
      <div className="space-y-6">
        <SuccessPanel
          eyebrow="Tutorial complete"
          title="You've seen the whole contract"
          actions={
            <>
              <ButtonLink href="/">Open the workbench</ButtonLink>
              <ButtonLink href="/learn/create" variant="secondary">
                Create another application
              </ButtonLink>
            </>
          }
        >
          <p>
            {recap.callbacks} signed callback{recap.callbacks === 1 ? '' : 's'} verified ·{' '}
            {recap.byRule} answer{recap.byRule === 1 ? '' : 's'} by rule, {recap.byAi} by AI,{' '}
            {recap.repaired} repaired
            {recap.lastTerminal
              ? ` · last application ${recap.lastTerminal.status}${
                  recap.lastTerminal.providerName ? ` (${recap.lastTerminal.providerName})` : ''
                }`
              : ''}
            .
          </p>
        </SuccessPanel>

        <StepColumns
          main={
            <ChecklistCard title="What's next" items={nextSteps} />
          }
          rail={
            <TeachPanel eyebrow="The contract in five lines" title="Everything that matters">
              <ol className="list-decimal space-y-1.5 pl-4">
                <li>Verify the HMAC over the raw bytes — never a re-serialisation.</li>
                <li>Dedupe on the event id; it is stable across retries.</li>
                <li>Answers travel in your HTTP response, inside 120s from created_at.</li>
                <li>A non-2xx fails the application instantly. Cancel cleanly instead.</li>
                <li>Corrections re-send everything; reply with a full snapshot. Three rounds, max.</li>
              </ol>
            </TeachPanel>
          }
        />
      </div>
    </SetupShell>
  )
}
