import Link from 'next/link'
import { desc } from 'drizzle-orm'
import { db } from '@/db/client'
import { profiles, type ApplicationRow, type WebhookEventRow } from '@/db/schema'
import { callbackUrl, config, configIssues } from '@/lib/config'
import { getSandboxScenarios } from '@/lib/jobo/client'
import { explainCode } from '@/lib/jobo/problem'
import type { SandboxScenario } from '@/lib/jobo/sandbox'
import { readSnippet } from '@/lib/snippets'
import { isTerminal } from '@/lib/status'
import {
  getNotebookState,
  getTutorialState,
  latestApplication,
  tutorialRecap
} from '@/lib/tutorial'
import type { AnswerCommand, FieldsRequestedEvent } from '@jobo-ai/autoapply'
import { SetupShell } from '@/components/SetupShell'
import { NotebookCell } from '@/components/NotebookCell'
import { TraceTable } from '@/components/TraceTable'
import { TeachPanel } from '@/components/TeachPanel'
import { CodeBlock } from '@/components/CodeBlock'
import { ChecklistCard, type ChecklistItem } from '@/components/ChecklistCard'
import { SuccessPanel } from '@/components/SuccessPanel'
import { PreflightRunner } from '@/components/PreflightRunner'
import { ApplyForm } from '@/components/ApplyForm'
import { StatusTimeline } from '@/components/StatusTimeline'
import { ApplicationInspector, loadApplicationView, type ApplicationView } from '@/components/ApplicationInspector'
import { PollingRefresher } from '@/components/PollingRefresher'
import { Accordion, Badge, ButtonLink, Json, Panel, StatusBadge } from '@/components/ui'

export const dynamic = 'force-dynamic'

/**
 * The tutorial — one page, notebook-style.
 *
 * Three cells, mirroring the three moments of the Auto Apply contract: the
 * request you make, the callback you receive, the response you return. Cells
 * unlock top to bottom, and every state is derived from real rows — see
 * lib/tutorial.ts. The page follows one application (?app=, else the newest)
 * and refreshes itself while that application is open, so the cells visibly
 * "run" as the webhook does its work.
 */

const ENV_CHECKS: { key: string; title: string; description: string }[] = [
  {
    key: 'JOBO_API_KEY',
    title: 'Jobo API key',
    description: 'A jbe_test_ or jbe_live_ key. Master keys are rejected on Auto Apply routes.'
  },
  {
    key: 'JOBO_WEBHOOK_SECRET',
    title: 'Webhook signing secret',
    description:
      'The whsec_ account secret, generated by PUT /api/auto-apply/settings on the portal API and revealed exactly once.'
  },
  {
    key: 'PUBLIC_BASE_URL',
    title: 'Public callback origin',
    description:
      'The https origin Jobo calls back on — your tunnel in development. Restart the dev server after changing it.'
  },
  {
    key: 'RESUME_URL_SIGNING_SECRET',
    title: 'Resume URL signing secret',
    description: 'Signs the short-lived resume download links. Generate with openssl rand -base64 32.'
  },
  {
    key: 'OPENROUTER_API_KEY',
    title: 'OpenRouter key',
    description: 'Answers the open-ended questions your deterministic rules cannot.'
  }
]

const CREATE_WIRE_SAMPLE = `POST /api/auto-apply/applications HTTP/1.1
Host: connect.jobo.world
X-Api-Key: jbe_test_...
Idempotency-Key: 3f6d1c2a-9d0e-4b7a-8f21-5a4c9e8b7d10
Content-Type: application/json

{
  "apply_url": "https://sandbox.jobo.world/ats/apply/...",
  "callback_url": "https://your-tunnel/api/jobo/webhook"
}

HTTP/1.1 202 Accepted
Location: /api/auto-apply/applications/{id}

{ "id": "...", "status": "queued", "provider_name": "..." }`

export default async function NotebookPage({
  searchParams
}: {
  searchParams: Promise<{ app?: string }>
}) {
  const { app: pinnedId } = await searchParams

  const issues = configIssues()
  const envReady = issues.length === 0

  // The application this notebook run follows.
  const targetId = pinnedId ?? latestApplication()?.id
  // Guarded on envReady: loading the view syncs against the Jobo API, which
  // needs a valid config. With a broken env the cells are locked anyway.
  const view = envReady && targetId ? await loadApplicationView(targetId) : null

  const nb = getNotebookState(envReady, view?.application ?? null, view?.events ?? [])
  const state = getTutorialState()

  const profileRows = db.select().from(profiles).orderBy(desc(profiles.createdAt)).all()

  // Sandbox scenarios degrade to the plain URL input, exactly like the form.
  let scenarios: SandboxScenario[] = []
  let sandboxAvailable = false
  let sandboxNote: string | null = null
  if (envReady) {
    try {
      const response = await getSandboxScenarios()
      sandboxAvailable = response.available
      scenarios = response.scenarios.filter((scenario) => scenario.apply_url)
      if (!response.available) sandboxNote = 'the sandbox is not enabled on this deployment yet'
      else if (scenarios.length === 0) sandboxNote = 'no scenarios are published right now'
    } catch (error) {
      sandboxNote = `could not load scenarios (${error instanceof Error ? error.message : String(error)})`
    }
  } else {
    sandboxNote = 'fix the environment first'
  }

  const cbUrl = envReady ? callbackUrl() : 'https://<PUBLIC_BASE_URL>/api/jobo/webhook'
  const application = view?.application ?? null
  const events = view?.events ?? []
  const polling =
    application !== null &&
    !isTerminal(application.status) &&
    application.status !== 'create_failed'

  return (
    <SetupShell
      eyebrow="Notebook"
      title="The whole contract, on one page"
      description="Three cells: the one request you make, the callback you receive, and the response you return — inside a 120-second window. Jobo stores no profile and generates no answers; everything interesting happens in your webhook."
    >
      <PollingRefresher active={polling} />

      <div className="space-y-6">
        {/* Nothing above cell 1 when the app can actually run — the notebook
            opens on the code, not on chrome. The setup panel is a failure
            state, not a permanent fixture. */}
        {!envReady && <SetupRequired issues={issues} />}

        {/* ── Cell 1 · create ─────────────────────────────────────────────── */}
        <NotebookCell
          index={1}
          title="Create the application"
          state={nb.create}
          lockedNote="setup incomplete"
          output={
            application ? <CreateOutput application={application} cbUrl={cbUrl} /> : undefined
          }
          footer={
            <>
              <Accordion eyebrow="The wire" title="What actually crosses the network">
                <CodeBlock label="The wire" language="http" code={CREATE_WIRE_SAMPLE} />
              </Accordion>
              <Accordion eyebrow="When create fails" title="The error taxonomy is part of the API">
                <ul className="list-disc space-y-1 pl-4 text-sm leading-6 text-ink-600">
                  <li>
                    <code className="code-chip text-xs">auto_apply_coming_soon</code> — creation is
                    deployment-gated (503). The verification ping from the runtime strip still
                    works.
                  </li>
                  <li>
                    <code className="code-chip text-xs">unsupported_ats</code> — no provider
                    matched the URL.
                  </li>
                  <li>
                    <code className="code-chip text-xs">unsafe_url</code> — the callback failed the
                    https/443/public-DNS rules.
                  </li>
                  <li>
                    <code className="code-chip text-xs">idempotency_key_reuse</code> — same key,
                    different body. Keys bind to the exact body for 24 hours.
                  </li>
                  <li>
                    <code className="code-chip text-xs">application_quota_exceeded</code> — 5 live
                    per 24h, 20 sandbox per hour, 5 in flight.
                  </li>
                </ul>
              </Accordion>
            </>
          }
        >
          <CodeBlock
            label="app/actions/applications.ts"
            language="ts"
            code={readSnippet('app/actions/applications.ts', 'The ordering here is the point', '.run()')}
          />
          <p className="text-sm leading-6 text-ink-600">
            The only request you make — one POST with an <code className="code-chip text-xs">Idempotency-Key</code>{' '}
            that is written to the local database <em>before</em> the network call, because a
            timed-out create can only be retried safely with the exact same key.
          </p>
          <div className="border-t hairline pt-4">
            <ApplyForm
              profiles={profileRows.map((p) => ({ id: p.id, name: p.name, isDefault: p.isDefault }))}
              scenarios={scenarios}
              sandboxAvailable={sandboxAvailable && scenarios.length > 0}
              sandboxNote={sandboxNote}
              defaultSandbox={envReady ? config().DEFAULT_SANDBOX : true}
              callbackUrl={cbUrl}
              redirectPrefix="/learn?app="
              runButton
            />
            <p className="mt-3 text-xs text-ink-500">
              Answers are produced from the selected profile. Two fictional samples ship with the
              app — add or edit profiles on the{' '}
              <Link href="/profiles" className="font-medium text-brand hover:text-brand-deep hover:underline">
                Profiles
              </Link>{' '}
              page.
            </p>
          </div>
        </NotebookCell>

        <TeachPanel eyebrow="Before the callback arrives" title="Never return a non-2xx" tone="warn">
          <p>
            Unlike most webhooks, a non-2xx response is not retried — it fails the application
            instantly with <code className="font-mono text-xs">callback_rejected</code>. The
            0s/5s/20s retries fire for transport errors only. If your handler breaks, return{' '}
            <code className="font-mono text-xs">200 {'{"action":"cancel"}'}</code>: a clean cancel
            instead of a dead application.
          </p>
        </TeachPanel>

        {/* ── Cell 2 · the callback ───────────────────────────────────────── */}
        <NotebookCell
          index={2}
          title="Jobo calls your webhook"
          state={nb.callback}
          lockedNote="waits on cell 1"
          output={application ? <CallbackOutput view={view!} /> : undefined}
          footer={
            <>
              <Accordion eyebrow="Signature" title="You do not write the crypto">
                <p className="text-sm leading-6 text-ink-600">
                  HMAC-SHA256 over{' '}
                  <code className="font-mono text-xs">
                    utf8(eventId + &quot;.&quot; + timestamp + &quot;.&quot;) &#8214; rawBody
                  </code>
                  , constant-time compared against every{' '}
                  <code className="font-mono text-xs">v1=</code> entry, inside a 300-second window —
                  all of it lives in <code className="font-mono text-xs">@jobo-ai/autoapply</code>.
                  Your side is naming the secret; the handler hands you a verified event plus the
                  exact bytes that were signed.
                </p>
              </Accordion>
              <Accordion eyebrow="Replay protection" title="Dedupe is a UNIQUE constraint">
                <p className="text-sm leading-6 text-ink-600">
                  <code className="font-mono text-xs">X-Jobo-Webhook-Id</code> is stable across
                  retries, so this app uses the <code className="font-mono text-xs">evt_</code>{' '}
                  value as the primary key of its events table. Claiming an event is one{' '}
                  <code className="font-mono text-xs">INSERT … ON CONFLICT DO NOTHING</code> — no
                  check-then-act race.
                </p>
              </Accordion>
            </>
          }
        >
          <CodeBlock
            label="app/api/jobo/webhook/route.ts"
            language="ts"
            code={readSnippet('app/api/jobo/webhook/route.ts', '*  1. NEVER RETURN A NON-2xx', 'is not.')}
          />
          <CodeBlock
            label="app/api/jobo/webhook/route.ts"
            language="ts"
            code={readSnippet(
              'app/api/jobo/webhook/route.ts',
              'let handler: ((request: Request)',
              'secret: config().JOBO_WEBHOOK_SECRET,'
            )}
          />
          <p className="text-sm leading-6 text-ink-600">
            This cell has no Run button — Jobo runs it. When the browser agent finds the form, it
            POSTs the fields to the callback URL above and waits, synchronously, for your answers.
          </p>
        </NotebookCell>

        {/* ── Cell 3 · the response ───────────────────────────────────────── */}
        <NotebookCell
          index={3}
          title="Your app answers — autonomously"
          state={nb.respond}
          lockedNote="waits on cell 2"
          output={application ? <RespondOutput application={application} events={events} /> : undefined}
          footer={
            <Accordion eyebrow="Correction rounds" title="When answers are rejected">
              <p className="text-sm leading-6 text-ink-600">
                Invalid answers come back as a new callback with{' '}
                <code className="font-mono text-xs">command_errors</code> and the FULL field list —
                your reply must be a complete snapshot, not a delta. After three rounds the
                application fails with{' '}
                <code className="font-mono text-xs">correction_limit_exceeded</code>, which is why
                this app validates locally with a port of Jobo&apos;s own validator before
                responding.
              </p>
            </Accordion>
          }
        >
          <CodeBlock
            label="lib/answers/index.ts"
            language="ts"
            code={readSnippet('lib/answers/index.ts', 'The answer pipeline:', 'round wasted.')}
          />
          <p className="text-sm leading-6 text-ink-600">
            This cell runs itself — the handler answered inside the callback window before this
            page could even refresh. The answers travel in the HTTP <em>response body</em> of cell
            2&apos;s request; there is no submit endpoint.
          </p>
        </NotebookCell>

        {view && (
          <Accordion
            eyebrow="Inspector"
            title="The full exchange — every event, raw bytes included"
            summary={`${events.length} event${events.length === 1 ? '' : 's'}`}
          >
            <ApplicationInspector view={view} />
          </Accordion>
        )}

        {state.complete && <CompletionFooter />}
      </div>
    </SetupShell>
  )
}

// ─── Setup failure state ─────────────────────────────────────────────────────

/**
 * Shown ONLY when the environment cannot work. There is no permanent "runtime"
 * chrome above the cells: when the app can run, the notebook opens on the code
 * rather than on a status bar you have already read once.
 */
function SetupRequired({ issues }: { issues: { key: string; message: string }[] }) {
  const issueByKey = new Map(issues.map((issue) => [issue.key, issue.message]))

  return (
    <Panel
      eyebrow="Before you can run this"
      title="Finish your setup"
      actions={
        <Badge tone="bad" dot>
          {issues.length} missing
        </Badge>
      }
    >
      <p className="text-sm leading-6 text-ink-600">
        Copy <code className="code-chip text-xs">.env.example</code> to{' '}
        <code className="code-chip text-xs">.env.local</code>, fill it in, and restart the dev
        server. The cells below unlock on their own once these pass.
      </p>

      <ul className="mt-4 divide-y hairline border-y hairline">
        {ENV_CHECKS.map((check) => {
          const problem = issueByKey.get(check.key)
          return (
            <li key={check.key} className="flex items-baseline gap-3 py-2.5 text-sm">
              <span
                className={`w-3 shrink-0 font-mono ${problem ? 'text-danger-deep' : 'text-success-deep'}`}
              >
                {problem ? '✗' : '✓'}
              </span>
              <div className="min-w-0">
                <code className="code-chip text-xs">{check.key}</code>
                <span className="ml-2 text-ink-600">{problem ?? check.description}</span>
              </div>
            </li>
          )
        })}
      </ul>

      <div className="mt-5">
        <PreflightRunner />
      </div>

      <div className="mt-5 border-t hairline pt-4">
        <p className="mb-2 text-sm leading-6 text-ink-600">
          Jobo only calls a public HTTPS URL on port 443 whose DNS resolves to a public address —
          localhost can never work, nor can a tunnel on a custom port. This app validates the same
          rules at boot:
        </p>
        <CodeBlock
          label="lib/config.ts"
          language="ts"
          code={readSnippet(
            'lib/config.ts',
            "if (url.port && url.port !== '443')",
            'must be publicly resolvable',
            2
          )}
        />
      </div>
    </Panel>
  )
}

// ─── Cell outputs ────────────────────────────────────────────────────────────

function latestFieldsEvent(events: WebhookEventRow[]): WebhookEventRow | undefined {
  return events.find((event) => event.type === 'application.fields_requested')
}

/** Cell 1's output: the create exchange, success or failure. */
function CreateOutput({ application, cbUrl }: { application: ApplicationRow; cbUrl: string }) {
  return (
    <>
      <div>
        <p className="mb-1 font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
          POST /api/auto-apply/applications
        </p>
        <Json
          value={{
            apply_url: application.applyUrl,
            callback_url: cbUrl,
            idempotency_key: application.idempotencyKey
          }}
        />
      </div>

      {application.status === 'creating' && (
        <p className="text-sm text-ink-600">Request in flight…</p>
      )}

      {application.joboApplicationId && (
        <div>
          <p className="mb-1 font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
            Response
          </p>
          <div className="mb-2">
            <Badge tone="good" dot>
              202 Accepted
            </Badge>
          </div>
          <Json
            value={{
              id: application.joboApplicationId,
              provider_name: application.providerName
            }}
          />
        </div>
      )}

      {application.status === 'create_failed' && (
        <div className="bg-danger-tint px-3 py-2 text-sm text-danger-deep">
          <code className="mr-2 font-mono text-xs">{application.createErrorCode}</code>
          {application.createErrorMessage}
          <span className="mt-1 block text-xs">
            Fix the cause and press Run again — a fresh row gets a fresh Idempotency-Key.
          </span>
        </div>
      )}
    </>
  )
}

/** Cell 2's output: the live timeline plus what Jobo actually sent. */
function CallbackOutput({ view }: { view: ApplicationView }) {
  const { application, events } = view
  const fields = latestFieldsEvent(events)

  let parsed: FieldsRequestedEvent | null = null
  if (fields) {
    try {
      parsed = JSON.parse(fields.rawBody) as FieldsRequestedEvent
    } catch {
      parsed = null
    }
  }

  return (
    <>
      <StatusTimeline application={application} events={events} />

      {!fields && !isTerminal(application.status) && (
        <p className="text-sm text-ink-600">
          Waiting for Jobo&apos;s browser agent to open the page and find the form — usually under
          a minute. This page refreshes itself.
        </p>
      )}

      {fields && (
        <div>
          <div className="flex flex-wrap items-center gap-2 text-sm">
            <Badge tone="good" dot>
              signature ok
            </Badge>
            <code className="font-mono text-[13px] font-medium text-ink-900">fields_requested</code>
            {(fields.correctionRound ?? 0) > 0 && (
              <Badge tone="warn">correction round {fields.correctionRound}</Badge>
            )}
            {parsed && (
              <span className="text-xs text-ink-500">{parsed.step.fields.length} fields</span>
            )}
            <span className="ml-auto font-mono text-[11px] text-ink-500">{fields.id}</span>
          </div>
          <p className="mb-1 mt-3 font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
            Request · what Jobo sent
          </p>
          <div className="max-h-96 overflow-y-auto">
            <Json value={parsed ?? fields.rawBody} />
          </div>
        </div>
      )}
    </>
  )
}

/** Cell 3's output: the response we returned, its provenance, and the outcome. */
function RespondOutput({
  application,
  events
}: {
  application: ApplicationRow
  events: WebhookEventRow[]
}) {
  const fields = latestFieldsEvent(events)

  let command: AnswerCommand | null = null
  if (fields?.responseBody) {
    try {
      command = JSON.parse(fields.responseBody) as AnswerCommand
    } catch {
      command = null
    }
  }

  const terminal = isTerminal(application.status)
  const gloss = application.failureCode ? explainCode(application.failureCode) : null

  return (
    <>
      {fields && !command && (
        <p className="text-sm text-ink-600">
          Your handler is generating answers inside the callback window…
        </p>
      )}

      {command && (
        <div>
          <div className="mb-1 flex items-center justify-between gap-3">
            <p className="font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
              Response · what we returned (HTTP 200)
            </p>
            {fields?.totalMs !== null && fields?.totalMs !== undefined && (
              <span className="text-xs tabular-nums text-ink-500">
                answered in {(fields.totalMs / 1000).toFixed(1)}s
              </span>
            )}
          </div>
          <div className="max-h-96 overflow-y-auto">
            <Json value={command} />
          </div>
        </div>
      )}

      {fields?.trace && fields.trace.length > 0 && (
        <div>
          <p className="mb-1 font-mono text-[11px] uppercase tracking-[0.05em] text-ink-500">
            How each field was answered
          </p>
          <TraceTable trace={fields.trace} />
        </div>
      )}

      {terminal && (
        <div className="flex flex-wrap items-center gap-3 border hairline bg-white px-3 py-2.5">
          <StatusBadge status={application.status} />
          <p className="text-sm text-ink-600">
            {application.status === 'submitted' &&
              'The form went through — Jobo delivered the terminal event and the exchange is complete.'}
            {application.status === 'failed' && (
              <>
                <code className="code-chip mr-2 text-xs">{application.failureCode}</code>
                {gloss ?? application.failureMessage}
              </>
            )}
            {application.status === 'canceled' &&
              'Canceled cleanly — a valid outcome, not an error.'}
          </p>
        </div>
      )}
    </>
  )
}

// ─── Completion footer ───────────────────────────────────────────────────────

function CompletionFooter() {
  const recap = tutorialRecap()

  const nextSteps: ChecklistItem[] = [
    {
      key: 'live',
      title: 'Rotate to live mode',
      description:
        'Swap jbe_test_ for jbe_live_ in .env.local and apply to a real job URL. Live quota is 5 creates per 24 hours.'
    },
    {
      key: 'correction',
      title: 'Trigger a correction round',
      description:
        'Edit your profile so an option cannot match (an unusual country spelling works), run cell 1 again, and watch the retry prompt carry you_sent and allowed_values.'
    },
    {
      key: 'harden',
      title: 'Harden for production',
      description:
        'A stable HTTPS origin instead of a quick tunnel, alerting on the delivery-attempts view, and a queue if your answer path outgrows one process.'
    },
    {
      key: 'files',
      title: 'Read the ★ files',
      description:
        'app/api/jobo/webhook/route.ts · lib/answers/validate.ts · lib/answers/index.ts — the whole integration is those three, because @jobo-ai/autoapply is the rest.'
    }
  ]

  return (
    <div className="space-y-6">
      <SuccessPanel
        eyebrow="Notebook complete"
        title="You've seen the whole contract"
        actions={
          <>
            <ButtonLink href="/">Open the workbench</ButtonLink>
            <ButtonLink href="#cell-1" variant="secondary">
              Run it again
            </ButtonLink>
          </>
        }
      >
        <p>
          {recap.callbacks} signed callback{recap.callbacks === 1 ? '' : 's'} verified ·{' '}
          {recap.byRule} answer{recap.byRule === 1 ? '' : 's'} by rule, {recap.byAi} by AI,{' '}
          {recap.repaired} repaired
          {recap.lastTerminal
            ? ` · last application ${recap.lastTerminal.status}${
                recap.lastTerminal.providerName ? ` (${recap.lastTerminal.providerName})` : ''
              }`
            : ''}
          .
        </p>
      </SuccessPanel>

      <ChecklistCard title="What's next" items={nextSteps} />

      <TeachPanel eyebrow="The contract in five lines" title="Everything that matters">
        <ol className="list-decimal space-y-1.5 pl-4">
          <li>Verify the HMAC over the raw bytes — never a re-serialisation.</li>
          <li>Dedupe on the event id; it is stable across retries.</li>
          <li>Answers travel in your HTTP response, inside 120s from created_at.</li>
          <li>A non-2xx fails the application instantly. Cancel cleanly instead.</li>
          <li>Corrections re-send everything; reply with a full snapshot. Three rounds, max.</li>
        </ol>
      </TeachPanel>
    </div>
  )
}
