/**
 * The one-time acknowledgement a candidate gives before their first
 * application. Answers here are generated by AI and submitted without the
 * candidate reviewing each one, so the Auto Apply Terms require the candidate
 * to accept that explicitly (not pre-ticked, not bundled into sign-up terms).
 *
 * Shared by the dialog (components/AiConsentDialog.tsx) and the server check
 * (app/actions/applications.ts). Changing the wording means bumping the
 * version, which asks everyone again.
 */
export const AI_CONSENT_VERSION = '2026-10-05'

export const AI_CONSENT_TITLE = 'Let AI answer your applications?'

export const AI_CONSENT_POINTS = [
  'AI writes answers to each application’s questions from your profile and resume, and submits the application for you.',
  'You won’t see each answer before it is sent.',
  'AI can make mistakes. An answer may be inaccurate or incomplete, and the employer receives it as yours.',
  'You can see every answer that was sent on the application’s page, and stop applying at any time.',
] as const

export const AI_CONSENT_CHECKBOX =
  'I allow AI to generate and submit answers for my applications, and I accept that it can make mistakes.'
